### ISSUE TITLE
apply PEP8 style to python files

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive-api#102]
set up clang-format for PEP8 if possible
apply style to existing code
remove unused functions

**Comment by AndrewJConley** [comment]
PEP8 is reporting, but we aren't doing anything about it.

**Comment by K20shores** [comment]
@mattldawson do you know the state of this now?

**Comment by K20shores** [comment]
#353 adds a github action to do this. pep8speaks used to work but appears to have gone down (https://github.com/pep8speaks-org/pep8speaks/issues/189). There are new maintainers (https://github.com/pep8speaks-org/pep8speaks/issues/191), but still the service appears to be down. We are abandoning it in favor of a pep8 PR
