### ISSUE TITLE
Slow responses from local web service while video conferencing

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive-api#171]
During a testing session, users experienced delayed responses after clicking buttons, links. Could be related to having a Google Meet running at the same time.

Try to recreate the problem, and see if accessing web service using 127.0.0.1 instead of localhost makes a difference:
https://stackoverflow.com/questions/2386299/running-sites-on-localhost-is-extremely-slow
https://stackoverflow.com/questions/362808/django-is-very-slow-on-my-machine

**Comment by K20shores** [comment]
@mattldawson can this be closed now?
