### ISSUE TITLE
Plot additional "evolving conditions"

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive-api#225]
I just ran the chapman mechanism and wanted to plot the photodecomp rates alongside the O3 concentrations just to know when the sun was shining.

Could we provide plots of any data that is read in as part of the "evolving conditions file"?

**Comment by K20shores** [comment]
@mattldawson did you complete this when we did the refactor?

**Comment by K20shores** [comment]
Yes, it is fixed
