### ISSUE TITLE
Add TS1 mechanism configuraiton and initial condtions

### ISSUE THREAD

**Issue by K20shores** [NCAR/music-box-interactive-api#420]
Add [TS1.zip](https://github.com/user-attachments/files/16433723/TS1.zip) as an example that can be retrieved by the API

**Acceptance criteria**
- in `interactive/api/static/examples` a new folder for TS1 is created with the proper mechanism and conditions
- `api/load-example?example=TS1` returns the TS1 configuration

**Comment by carl-drews** [comment]
Here is the test URL on my Docker installation:
	http://localhost:8000/api/load-example?example=TS1

You should see some JSON that is the contents of the files I have placed in:
C:\2024\MusicBox\music-box-interactive-api\interactive\api\static\examples\TS1>

**Comment by carl-drews** [comment]
Branch **add-TS1** is pushed, merged, and pruned.
https://github.com/NCAR/music-box-interactive-api/pull/421

TS1 runs to completion with MusicBox and produces CSV output. We temporarily removed the initial conditions, and the output values are all zeros (except for temp 206.6374 and press 6152.05).
